# Generated by Django 6.1 on 2026-09-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='blocked_util',
            new_name='blocked_until',
        ),
    ]
